###########################################################################
#
# Generated by : Version 10.1 Build 197 01/19/2011 Service Pack 1 SJ Web Edition
#
# Project      : Tetris_DE1
# Revision     : Tetris_DE1
#
# Date         : Sun Mar 27 17:55:35 CEST 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: CLOCK_27[0]
create_clock -period "20 ns" \
             -name {CLOCK_50} {CLOCK_50}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------

